name: Twitch Live Status

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Check Twitch live status
      id: twitch-status
      env:
        TWITCH_USERNAME: tommertyboi
      run: |
        LIVE_STATUS=$(curl -s -H "Accept: application/vnd.twitchtv.v5+json" \
          -X GET "https://api.twitch.tv/kraken/streams/$TWITCH_USERNAME")
        
        if [ "$(echo $LIVE_STATUS | jq -r '.stream')" != "null" ]; then
          echo "::set-output name=live_status::true"
        else
          echo "::set-output name=live_status::false"
        fi

    - name: Update README
      env:
        LIVE_STATUS: ${{ steps.twitch-status.outputs.live_status }}
      run: |
        if [ "$LIVE_STATUS" == "true" ]; then
          sed -i '1i\[![Twitch Live Banner](/assets/livebanner.png)](https://www.twitch.tv/tommerty)' README.md
        else
         sed -i '/^!\[Twitch Live Banner/d' README.md
        fi

    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        git commit -m "Update Twitch live status in README"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
