name: Twitch Live Status

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.6

    - name: Check Twitch live status
      id: twitch-status
      run: |
        live_status=$(curl -s https://api.doras.to/links/twitch/tommertyboi | jq -r '.live')
        echo "live_status=$live_status" >> $GITHUB_OUTPUT

    - name: Update README
      env:
        LIVE_STATUS: ${{ steps.twitch-status.outputs.live_status }}
      run: |
        echo "Live Status: $LIVE_STATUS"
        if [ "$LIVE_STATUS" == "true" ]; then
          if ! grep -q "Twitch Live Banner" README.md; then
            sed -i '1i\[![Twitch Live Banner](/assets/livebanner.png)](https://www.twitch.tv/tommertyboi)' README.md
          fi
        else
          sed -i '/\[!\[Twitch Live Banner\](\/assets\/livebanner\.png)\]\(https:\/\/www\.twitch\.tv\/tommertyboi\)/d' README.md
          echo "Removed Twitch Live Banner"
        fi

    - name: Check for changes
      run: |
        git diff
        if [ -n "$(git status --porcelain)" ]; then
          echo "Changes detected"
        else
          echo "No changes detected"
        fi

    - name: Commit changes
      if: always()
      run: |
        git config --global user.email "tommerty@github.com"
        git config --global user.name "Tommerty"
        git add .
        git commit -m "twitch update"
        git push
