name: Update Socials

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # Runs every 24 hours
  workflow_dispatch:

jobs:
  update-socials:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.6

    - name: Fetch socials
      id: fetch-socials
      run: |
        socials=$(curl -s https://doras.to/api/user/tommerty/blocks)
        echo "socials=$socials" >> $GITHUB_OUTPUT

    - name: Update README
      env:
        SOCIALS: ${{ steps.fetch-socials.outputs.socials }}
      run: |
        # Remove existing socials between the comments
        sed -i '/<!-- Social Start -->/,/<!-- Socials End -->/d' README.md
        
        # Add new socials between the comments
        socials=$(curl -s https://doras.to/api/user/tommerty/blocks | jq -r '.[] | select(.show == true and .type == "link") | "- [<img src=\"" + .icon + "\" alt=\"" + .name + "\" width=\"20\" height=\"20\"> " + .name + "](" + .url + ")"')
        echo "<!-- Social Start -->" >> README.md
        echo "$socials" >> README.md
        echo "<!-- Socials End -->" >> README.md

    - name: Commit changes
      run: |
        git config --local user.email "tommerty@github.com"
        git config --local user.name "Tommerty"
        git add README.md
        git diff-index --quiet HEAD || git commit -m "Update socials in README"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
